import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
;('use client')

import { useRouter } from 'next/navigation'
import { useEffect } from 'react'

export default function RootLayout({ children }) {
	const router = useRouter()

	useEffect(() => {
		const handleMessage = event => {
			if (event.data.type === 'vk-auth-success') {
				localStorage.setItem('vkAccessToken', event.data.token)
				localStorage.setItem('vkUserId', event.data.userId)
				router.push('/profile')
			}
		}

		window.addEventListener('message', handleMessage)
		return () => window.removeEventListener('message', handleMessage)
	}, [router])

	return <>{children}</>
}
